### PR TITLE
⭐ example showcasing animated storm and drifters plots

### PR DESCRIPTION
**Pull request by kevinsantana11**

### CODE REVIEW

**Comment by selipot** [comment]
- Need to update the access to the gdp 6 hour zarr file by removing the change of variables.
- I notice that the gdp6h and hurdat2 datasets do not have the same encoding of the time. If they did you could use exactly the same dictionary to pass to subset to apply to both datasets. I think this can be fixed now by setting decodes_time=True for the gdp dataset as in `drifter_ds = xr.open_dataset(url, decode_times=True, engine="zarr")`.

**Comment by kevinsantana11** [comment]
@selipot please have a look at the example I simplified it a good bit

**Comment by selipot** [comment]
I think it would be beneficial to simplify the handling of times. As I mentioned before we should be able to have a unique `criteria` to pass to the drifter dataset and the hurdat2 dataset. Right now we use `datetime` objects, `numpy.datetime64` objects, and finally `pandas.date_range` 🤪

**Comment by kevinsantana11** [comment]
@selipot I think this is ready please have a look

**Comment by kevinsantana11** [comment]
forgot to include the output, adding now

**Comment by selipot** [comment]
@kevinsantana11 you lost the latitude and longitude grid and tick labels in the latest versions.

**Comment by kevinsantana11** [comment]
@selipot I think it looks cleaner this way IMO but if you think its worth adding I can do taht

**Comment by selipot** [comment]
You can remove the grid if you prefer but ticks and labels are a must

**Comment by kevinsantana11** [comment]
@selipot added them back, think we should be good now

**Pull request merged**
